---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# unjoin

The goal of unjoin is to provide `unjoin` for data frames. This is used to build topological data structures, with a
kind of inside-out version of a nested data frame. Whether it's of broader use is an open question. 

## Installation

You can install unjoin from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("mdsumner/unjoin")
```

## Example

This is a basic example which shows you how to unjoin a data frame. 

```{r example}
library(unjoin)

unjoin(iris)

library(dplyr)
iris %>% unjoin(Species)

iris %>% unjoin(Species, Petal.Width)
```


```{r quakes}
uj_q <- unjoin(quakes,  long, lat, depth)

library(dplyr)
## what is uj_q?  (it's a MULTIPOINT structure)
g <- sf::st_sfc(uj_q$main %>% split(.$.idx0) %>% 
  purrr::map(function(x) sf::st_multipoint(as.matrix(inner_join(x, uj_q$data[, ".idx0"], ".idx0") %>% dplyr::select(-.idx0)))), 
  crs = 4326)
sfd <- sf::st_sf(uj_q$data, geometry = g)


```
